version: '3'
services:
  mongo:
    image: mongo
    container_name: inspiration-point-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
  backend: 
    container_name: inspiration-point-backend
    build: 
      context: ./
    depends_on:
    - mongo
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=mongo