version: '3'
services:
  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      # Elasticsearch 8.x has HTTPS and auth on by default. This option is
      # needed to use HTTP and no auth (as used in the tests).
      - xpack.security.enabled=false
    container_name: elasticsearch
    ports: ['9200:9200']
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    hostname: kibana
    image: kibana:8.8.2
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']
    networks:
      - elk

  prometheus: 
    image: prom/prometheus:v2.30.3
    ports: 
     - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.1.3
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always
    env_file: 
      .env

  mongo:
    image: mongo
    container_name: inspiration-point-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
    networks:
      - elk

  backend: 
    hostname: inspiration-point-backend
    container_name: inspiration-point-backend
    build: 
      context: ./
    restart: unless-stopped
    depends_on:
      - mongo
      - elasticsearch
    environment:
      - ES_HOST=elasticsearch
      - MONGO_HOST=mongo
    
    ports:
      - 3000:3000
    networks:
      - elk

networks:
  elk: 
    driver: bridge

volumes: 
  elasticsearch: